name: Deployment to AWS EB
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build 

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Latest Repo
      uses: actions/checkout@master

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish -c Release -o '${{ github.workspace }}/out'
  
    - name: Zip Package
      run: |
        cd ${{ github.workspace }}/out 
        zip -r ${{ github.workspace }}/out.zip *

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: event-organizer
        environment_name: eo-identity-server-prod
        region: eu-north-1
        version_label: ${{ github.run_id }}
        version_description: ${{ github.sha }}
        deployment_package: ${{ github.workspace }}/out.zip